dist: trusty
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
install:
  - npm install
before_script:
  - npm run build
  - npm install -g ./
script:
  - npm run lint
  - npm run integration:test
  - npm run cli:test
