sudo: required
dist: bionic
language: node_js
node_js:
  - 10
install:
  - npm install
before_script:
  - npm run build
  - npm install -g ./
script:
  - cat /etc/passwd
  - groups
  - whoami
  - npm run lint
  - npm run integration:test
  - npm run cli:test
